### ISSUE TITLE
Cannot reader HalosGoneMad data

### ISSUE THREAD

**Issue by lyang36** [sbird/GadgetReader#2]
Hi, 

The code reports there's no datablock in the following gadget file. 
http://popia.ft.uam.es/public/HaloesGoingMAD/DATA/

Probably a bug.

Best,

**Comment by sbird** [comment]
Hi,

Those gadget files are gadget-1 format, which is a little tricky to read correctly, so bugs are a possibility. I seem to be able to extract header information from http://popia.ft.uam.es/public/HaloesGoingMAD/DATA/MockHaloes/blind  successfully. 

% ./PGIIhead blind 
[GadgetReader]: WARNING: Reading Gadget-I file using pre-computed
block order, which may not correspond to the actual order of your file!
0 1591915 0 0 0 0
0.000000 0.010000 0.000000 0.000000 0.000000 0.000000
1.000000
0
0
0
0 1591915 0 0 0 0
0
1
1.000000e+02
0.3
0.7
0.73
0
0
Non-head blocks found:
ID   with 1591915 particles, in 6367660 bytes.
POS  with 1591915 particles, in 19102980 bytes.
VEL  with 1591915 particles, in 19102980 bytes.

Could you please give a little more detail on the problem?
Which file do you use, and what exactly how do you extract the data?

Thanks,
Simeon

**Comment by lyang36** [comment]
Hi Simeon,

Thank you for quick response. I'm trying to read this one:
http://popia.ft.uam.es/public/HaloesGoingMAD/DATA/FullBox/0256/FullBox_z0.0_0256

Use the example PGIIhead, the outputs are as following:
[GadgetReader]: WARNING: Endianness swapped
[GadgetReader]: SetBlockTypes failed for block POS  in file /data2/data/HalosGoneMad/FullBox/256/FullBox_z0.0_0256, length 402653184
[GadgetReader]: SetBlockTypes failed for block VEL  in file /data2/data/HalosGoneMad/FullBox/256/FullBox_z0.0_0256, length 402653184
[GadgetReader]: SetBlockTypes failed for block ID   in file /data2/data/HalosGoneMad/FullBox/256/FullBox_z0.0_0256, length 134217728
[GadgetReader]: SetBlockTypes failed for block MASS in file /data2/data/HalosGoneMad/FullBox/256/FullBox_z0.0_0256, length 67108864
[GadgetReader]: SetBlockTypes failed for block U    in file /data2/data/HalosGoneMad/FullBox/256/FullBox_z0.0_0256, length 67108864
[GadgetReader]: SetBlockTypes failed for block RHO  in file /data2/data/HalosGoneMad/FullBox/256/FullBox_z0.0_0256, length 67108864
Unable to load file. Probably does not exist


While use the default read_gadget.c, by setting version=1, swap=true, and id_type=long long. I can successfully read the data.

Best,

**Comment by sbird** [comment]
This should be fixed by b8fc481f76b726e70daaa3b6244d6830410a02ce

Turns out detecting endianness was implemented, but swapping it wasn't!
