### ISSUE TITLE
No Mass Block

### ISSUE THREAD

**Issue by DCunnama** [sbird/GadgetReader#4]
Hi Simeon,

Thank you for making this public, I have been doing some testing and I noticed that you don't take into account the standard gadget behaviour for when there is no MASS block.

Normally if the mass is given in the header then a mass block is skipped.

It seems the reader persists in reading a MASS block when it should be U.

Kind Regards,
Daniel

**Comment by sbird** [comment]
Hi Daniel,

This should be fixed by commit 2c0ede25400668c23d01b775ac5c7bfe89eefbc9

Please try it and let me know if it works
Simeon

**Comment by DCunnama** [comment]
Hi Simeon,

Yes, that seems to have fixed it.

Kind Regards,
Daniel
