### ISSUE TITLE
HDF5 include and linking

### ISSUE THREAD

**Issue by Ganondolf** [sbird/GadgetReader#5]
In recent versions of Ubuntu (or, at least, in Linux Mint 18) hdf5 headers and libraries are not in the standard directories, but rather in subfolders:
/usr/include/hdf5/serial
/usr/lib/x86_64-linux-gnu/hdf5/serial
as a result, the compilation fails unless you manually include those folders.

Please update the Makefile accordingly. Thanks!

**Comment by sbird** [comment]
I see they have renamed the libraries as well. Wonderful. 

The reason for doing this unpleasant thing is probably to make the parallel and serial versions of HDF5 co-installable, so the obvious way to make it less unpleasant is to add an alternatives rule that chooses which hdf5 is to be default, and symlinks /usr/include/hdf5.h accordingly. Could you possibly double-check for me that the problem is not just that this is broken on your system?

I think you want to run something like:
update-alternatives --display hdf5
(see also: https://wiki.debian.org/DebianAlternatives and http://linux.die.net/man/8/update-alternatives)

**Comment by Ganondolf** [comment]
It is indeed, I have /usr/.../hdf5/serial and /usr/.../hdf5/openmpi installed side-by-side.

There is no alternative for hdf5, and no symlink in a more standard location. My system is a recent fresh install, so I doubt there is something broken on my side.
Moreover, instead of just hdf5.h and hdf5_hl.h there are now 110 files in the include directory, so I guess they didn't want to pollute /usr/include with that many files.

**Comment by sbird** [comment]
110 files! And several of them seem to be fortran modules at that. Ok, I retract my insinuations about ubuntu - hdf5 is the one doing the crazy. Let me fix up the Makefile.

**Comment by sbird** [comment]
Try commit : https://github.com/sbird/GadgetReader/commit/86a1574a77128e233efff5924b5f23af938b2776

**Comment by Ganondolf** [comment]
Still not working, ifeq (PKG,0) is false and it goes in the else branch.
Output of pkg-config --exists hdf5-serial is empty (pkg-config --libs and pkg-config --cflags both work, though)

**Comment by sbird** [comment]
Try https://github.com/sbird/GadgetReader/commit/579391ccd84cb80908269e4f1e18c07e398d4812 ?

**Comment by Ganondolf** [comment]
Working now.
Well, for this issue at least, it still fails to compile libwgad.so (undefined reference to H5LTset_attribute_int, H5LTset_attribute_double and H5LTset_attribute_uint). Maybe they moved something away from hdf5.h? It seems they are in H5LTpublic.h now.

**Comment by sbird** [comment]
Is that failure at link time? In which case can you try adding "-lhdf5_hl" to line 17 of the Makefile?

**Comment by Ganondolf** [comment]
Yes, it was missing. Confirmed working now.

**Comment by Ganondolf** [comment]
I also found that /usr/lib/x86_64-linux-gnu/pkgconfig/hdf5.pc is a symlink to /etc/alternatives/hdf5.pc (which in my installation points to /usr/lib/x86_64-linux-gnu/pkgconfig/hdf5-serial.pc), so there actually is and alternative in the end.

**Comment by sbird** [comment]
Good - that will let us compile in case someone has the parallel HDF5 but not serial. I'll update the Makefile in the morning.

**Comment by sbird** [comment]
Latest version should fix it.
