### ISSUE TITLE
make: *** [librgad.so.1] Error 1

### ISSUE THREAD

**Issue by rebecamc** [sbird/GadgetReader#6]
I have run make on your code, and I got this:

cc gadgetreader.o -shared -Wl,-soname,librgad.so.1,--no-add-needed,--as-needed -o librgad.so.1
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [librgad.so.1] Error 1

I'm working on Mac, and I don't know if I have to install anything else.
Thanks

**Comment by sbird** [comment]
Thanks - which Mac version are you using? (the output of cc --version) would be good too.

**Comment by rebecamc** [comment]
I'm using Sierra and: 

Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by sbird** [comment]
Try it now? I have only compiled with HDF5 and BigFile disabled in the Makefile.
It looks like you are actually the first person to try to compile on Mac, so be warned that this is entirely untested!

**Comment by rebecamc** [comment]
I tried your suggestion, but it didn't work.

**Comment by sbird** [comment]
Did you git pull? It should at least give a different error...

**Comment by rebecamc** [comment]
I'm sorry I don't know what do you mean by "git pull"

**Comment by sbird** [comment]
I need you to update to the latest version of the code. How did you do that?

In the Makefile you should now have a line like 'LDCHECK:=$(shell ld -soname 2>&1)'.

If it is there you should do 'make clean' and then 'make' and it should compile.

**Comment by rebecamc** [comment]
That work, thank you. 
But now I'm running the make for GenPk and I got this (note: I have the brew version of openmpi): 
make[1]: `librgad.so' is up to date.
c++ -O2 -ffast-math -g -c -Wall -fopenmp  -I/Users/RebecaMc/GenPK-master/GadgetReader    -c -o gen-pk.o gen-pk.cpp
clang: error: unsupported option '-fopenmp'
make: *** [gen-pk.o] Error 1

**Comment by sbird** [comment]
GenPK uses openmp for shared memory parallelization (not MPI). 
This isn't supported by apple's clang. I suggest either:
a) deleting '-fopenmp' from GenPK's Makefile (which will be very slow).
b) Installing gcc from homebrew and compiling with that (better)
